import Head from 'next/head';
import AppBanner from '../src/components/AppBanner';
import AppGallery from '../src/components/AppGallery';

export default function Gallery() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBanner
        size="L"
        title=""
        subTitle=""
        breadcrumbs={[
          {
            label: 'Accueil',
            url: '/',
          },
          {
            label: 'Galerie',
            url: '/gallery',
          },
        ]}
      />
      <AppGallery />
    </div>
  );
}
