import Head from 'next/head';
import AboutUs from '../src/components/AboutUs';
import AppBanner from '../src/components/AppBanner';
import RestaurantQuickCard from '../src/components/RestaurantQuickCard';
import RoomQuickCard from '../src/components/RoomQuickCard';
import StartReservationForm from '../src/components/StartReservationForm';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBanner
        size="L"
        title="Bienvenue au Refuge HULMAN"
        subTitle="Ici vous êtes chez vous. Tous les services sont optimisés afin que vous passiez le meilleur moment possible. Un cadre calme et agréable, une chaleureuse, une table de qualité, tout cela servi avec une constante bonne humeur. Alors n'attendez plus et venez nous voir, nous vous attendons."
        breadcrumbs={[
          {
            label: 'Accueil',
            url: '/',
          },
        ]}
      />
      <StartReservationForm />
      <div className="container">
        <AboutUs />
        <RoomQuickCard />
        <RestaurantQuickCard />
      </div>
    </div>
  );
}
