import Head from 'next/head';
import AppBanner from '../src/components/Common/AppBanner';
import ReservationFormManager from '../src/components/Forms/ReservationFormManager';

export default function ReservationLanding() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBanner
        size="L"
        title="N'attendez plus..."
        subTitle="Réservez votre séjour de rêve au refuge HULMAN, nous vous attendons"
        breadcrumbs={[
          {
            label: 'Accueil',
            url: '/',
          },
          {
            label: 'Réserver',
            url: '/reserver',
          },
        ]}
      />
      <ReservationFormManager />
    </div>
  );
}
